# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qdisplay.Ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Qdisplay(object):
    def setupUi(self, Qdisplay):
        Qdisplay.setObjectName("Qdisplay")
        Qdisplay.resize(360, 320)
        Qdisplay.setMinimumSize(QtCore.QSize(360, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Qdisplay.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Qdisplay)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RTK_State_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.RTK_State_Text.setFont(font)
        self.RTK_State_Text.setText("")
        self.RTK_State_Text.setObjectName("RTK_State_Text")
        self.gridLayout_2.addWidget(self.RTK_State_Text, 8, 1, 1, 1)
        self.RTK_Heading_Flag_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.RTK_Heading_Flag_Text.setFont(font)
        self.RTK_Heading_Flag_Text.setText("")
        self.RTK_Heading_Flag_Text.setObjectName("RTK_Heading_Flag_Text")
        self.gridLayout_2.addWidget(self.RTK_Heading_Flag_Text, 9, 1, 1, 1)
        self.label_R10 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R10.setFont(font)
        self.label_R10.setObjectName("label_R10")
        self.gridLayout_2.addWidget(self.label_R10, 13, 0, 1, 1)
        self.label_R8 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R8.setFont(font)
        self.label_R8.setObjectName("label_R8")
        self.gridLayout_2.addWidget(self.label_R8, 9, 0, 1, 1)
        self.label_R7 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R7.setFont(font)
        self.label_R7.setObjectName("label_R7")
        self.gridLayout_2.addWidget(self.label_R7, 8, 0, 1, 1)
        self.label_R9 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R9.setFont(font)
        self.label_R9.setObjectName("label_R9")
        self.gridLayout_2.addWidget(self.label_R9, 10, 0, 1, 1)
        self.Altitude_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Altitude_Text.setFont(font)
        self.Altitude_Text.setText("")
        self.Altitude_Text.setObjectName("Altitude_Text")
        self.gridLayout_2.addWidget(self.Altitude_Text, 13, 1, 1, 1)
        self.UTC_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.UTC_Text.setFont(font)
        self.UTC_Text.setText("")
        self.UTC_Text.setObjectName("UTC_Text")
        self.gridLayout_2.addWidget(self.UTC_Text, 5, 1, 1, 1)
        self.Heading_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Heading_Text.setFont(font)
        self.Heading_Text.setText("")
        self.Heading_Text.setObjectName("Heading_Text")
        self.gridLayout_2.addWidget(self.Heading_Text, 4, 1, 1, 1)
        self.label_R3 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R3.setFont(font)
        self.label_R3.setObjectName("label_R3")
        self.gridLayout_2.addWidget(self.label_R3, 2, 0, 1, 1)
        self.Latitude_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Latitude_Text.setFont(font)
        self.Latitude_Text.setText("")
        self.Latitude_Text.setObjectName("Latitude_Text")
        self.gridLayout_2.addWidget(self.Latitude_Text, 0, 1, 1, 1)
        self.label_R2 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R2.setFont(font)
        self.label_R2.setObjectName("label_R2")
        self.gridLayout_2.addWidget(self.label_R2, 1, 0, 1, 1)
        self.Longitude_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Longitude_Text.setFont(font)
        self.Longitude_Text.setText("")
        self.Longitude_Text.setObjectName("Longitude_Text")
        self.gridLayout_2.addWidget(self.Longitude_Text, 1, 1, 1, 1)
        self.East_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.East_Text.setFont(font)
        self.East_Text.setText("")
        self.East_Text.setObjectName("East_Text")
        self.gridLayout_2.addWidget(self.East_Text, 2, 1, 1, 1)
        self.North_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.North_Text.setFont(font)
        self.North_Text.setText("")
        self.North_Text.setObjectName("North_Text")
        self.gridLayout_2.addWidget(self.North_Text, 3, 1, 1, 1)
        self.label_R5 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R5.setFont(font)
        self.label_R5.setObjectName("label_R5")
        self.gridLayout_2.addWidget(self.label_R5, 4, 0, 1, 1)
        self.label_R4 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R4.setFont(font)
        self.label_R4.setObjectName("label_R4")
        self.gridLayout_2.addWidget(self.label_R4, 3, 0, 1, 1)
        self.label_R1 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R1.setFont(font)
        self.label_R1.setObjectName("label_R1")
        self.gridLayout_2.addWidget(self.label_R1, 0, 0, 1, 1)
        self.None_Text2_2 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.None_Text2_2.setFont(font)
        self.None_Text2_2.setText("")
        self.None_Text2_2.setObjectName("None_Text2_2")
        self.gridLayout_2.addWidget(self.None_Text2_2, 14, 1, 1, 1)
        self.label_R6 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R6.setFont(font)
        self.label_R6.setObjectName("label_R6")
        self.gridLayout_2.addWidget(self.label_R6, 5, 0, 1, 1)
        self.Speed_Text = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Speed_Text.setFont(font)
        self.Speed_Text.setText("")
        self.Speed_Text.setObjectName("Speed_Text")
        self.gridLayout_2.addWidget(self.Speed_Text, 10, 1, 1, 1)
        self.label_R11 = QtWidgets.QLabel(Qdisplay)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_R11.setFont(font)
        self.label_R11.setText("")
        self.label_R11.setObjectName("label_R11")
        self.gridLayout_2.addWidget(self.label_R11, 14, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Qdisplay)
        QtCore.QMetaObject.connectSlotsByName(Qdisplay)

    def retranslateUi(self, Qdisplay):
        _translate = QtCore.QCoreApplication.translate
        Qdisplay.setWindowTitle(_translate("Qdisplay", "Form"))
        self.label_R10.setText(_translate("Qdisplay", "Altitude："))
        self.label_R8.setText(_translate("Qdisplay", "RTK Heading Flag:"))
        self.label_R7.setText(_translate("Qdisplay", "RTK State:"))
        self.label_R9.setText(_translate("Qdisplay", "Speed:"))
        self.label_R3.setText(_translate("Qdisplay", "East:"))
        self.label_R2.setText(_translate("Qdisplay", "Longitude:"))
        self.label_R5.setText(_translate("Qdisplay", "Heading:"))
        self.label_R4.setText(_translate("Qdisplay", "North:"))
        self.label_R1.setText(_translate("Qdisplay", "Latitude:"))
        self.label_R6.setText(_translate("Qdisplay", "UTC:"))

import apprcc_rc
