# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uu.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        font = QtGui.QFont()
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralWidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1400, 800))
        self.mdiArea.setMinimumSize(QtCore.QSize(1400, 700))
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 31))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuWindow = QtWidgets.QMenu(self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Device_List = QtWidgets.QDockWidget(MainWindow)
        self.Device_List.setMinimumSize(QtCore.QSize(200, 700))
        self.Device_List.setMaximumSize(QtCore.QSize(200, 700))
        self.Device_List.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.Device_List.setObjectName("Device_List")
        self.dockWidgetContents_Device_List = QtWidgets.QWidget()
        self.dockWidgetContents_Device_List.setObjectName("dockWidgetContents_Device_List")
        self.Serial_GroupBox = QtWidgets.QGroupBox(self.dockWidgetContents_Device_List)
        self.Serial_GroupBox.setGeometry(QtCore.QRect(10, 10, 181, 381))
        self.Serial_GroupBox.setObjectName("Serial_GroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.Serial_GroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Lab_Serial_1 = QtWidgets.QLabel(self.Serial_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Lab_Serial_1.setFont(font)
        self.Lab_Serial_1.setObjectName("Lab_Serial_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_1)
        self.Check_Button = QtWidgets.QPushButton(self.Serial_GroupBox)
        self.Check_Button.setAutoRepeatInterval(100)
        self.Check_Button.setDefault(True)
        self.Check_Button.setObjectName("Check_Button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Check_Button)
        self.Lab_Serial_2 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_2.setObjectName("Lab_Serial_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_2)
        self.Choice_ComboBox = QtWidgets.QComboBox(self.Serial_GroupBox)
        self.Choice_ComboBox.setObjectName("Choice_ComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Choice_ComboBox)
        self.State_Label = QtWidgets.QLabel(self.Serial_GroupBox)
        self.State_Label.setText("")
        self.State_Label.setTextFormat(QtCore.Qt.AutoText)
        self.State_Label.setScaledContents(True)
        self.State_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.State_Label.setObjectName("State_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.State_Label)
        self.Lab_Serial_3 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_3.setObjectName("Lab_Serial_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_3)
        self.Baudrate_ComboBox = QtWidgets.QComboBox(self.Serial_GroupBox)
        self.Baudrate_ComboBox.setObjectName("Baudrate_ComboBox")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.Baudrate_ComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Baudrate_ComboBox)
        self.Lab_Serial_4 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_4.setObjectName("Lab_Serial_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_4)
        self.Bytesize_ComboBox = QtWidgets.QComboBox(self.Serial_GroupBox)
        self.Bytesize_ComboBox.setObjectName("Bytesize_ComboBox")
        self.Bytesize_ComboBox.addItem("")
        self.Bytesize_ComboBox.addItem("")
        self.Bytesize_ComboBox.addItem("")
        self.Bytesize_ComboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Bytesize_ComboBox)
        self.Lab_Serial_5 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_5.setObjectName("Lab_Serial_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_5)
        self.Parity_ComboBox = QtWidgets.QComboBox(self.Serial_GroupBox)
        self.Parity_ComboBox.setObjectName("Parity_ComboBox")
        self.Parity_ComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Parity_ComboBox)
        self.Lab_Serial_6 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_6.setObjectName("Lab_Serial_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_6)
        self.Stopbits_ComboBox = QtWidgets.QComboBox(self.Serial_GroupBox)
        self.Stopbits_ComboBox.setObjectName("Stopbits_ComboBox")
        self.Stopbits_ComboBox.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Stopbits_ComboBox)
        self.Open_Button = QtWidgets.QPushButton(self.Serial_GroupBox)
        self.Open_Button.setObjectName("Open_Button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.Open_Button)
        self.Close_Button = QtWidgets.QPushButton(self.Serial_GroupBox)
        self.Close_Button.setObjectName("Close_Button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.Close_Button)
        self.Lab_Serial_7 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_7.setObjectName("Lab_Serial_7")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_7)
        self.Receive_LineEdit = QtWidgets.QLineEdit(self.Serial_GroupBox)
        self.Receive_LineEdit.setObjectName("Receive_LineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.Receive_LineEdit)
        self.Lab_Serial_8 = QtWidgets.QLabel(self.Serial_GroupBox)
        self.Lab_Serial_8.setObjectName("Lab_Serial_8")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.Lab_Serial_8)
        self.Send_LineEdit = QtWidgets.QLineEdit(self.Serial_GroupBox)
        self.Send_LineEdit.setObjectName("Send_LineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.Send_LineEdit)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents_Device_List)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 400, 181, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Setting_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Setting_Button.setGeometry(QtCore.QRect(50, 110, 75, 23))
        self.Setting_Button.setObjectName("Setting_Button")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 28, 128, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_X = QtWidgets.QLabel(self.layoutWidget)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout.addWidget(self.label_X)
        self.X_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.X_LineEdit.setMaximumSize(QtCore.QSize(90, 20))
        self.X_LineEdit.setObjectName("X_LineEdit")
        self.horizontalLayout.addWidget(self.X_LineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 54, 128, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Y = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_2.addWidget(self.label_Y)
        self.Y_LineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Y_LineEdit.setMaximumSize(QtCore.QSize(90, 20))
        self.Y_LineEdit.setObjectName("Y_LineEdit")
        self.horizontalLayout_2.addWidget(self.Y_LineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 80, 128, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Z = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_3.addWidget(self.label_Z)
        self.Z_LineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Z_LineEdit.setMaximumSize(QtCore.QSize(90, 20))
        self.Z_LineEdit.setObjectName("Z_LineEdit")
        self.horizontalLayout_3.addWidget(self.Z_LineEdit)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_Device_List)
        self.groupBox.setGeometry(QtCore.QRect(10, 550, 181, 121))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(16, 23, 131, 91))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Start_Plot_Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.Start_Plot_Button.setObjectName("Start_Plot_Button")
        self.verticalLayout.addWidget(self.Start_Plot_Button)
        self.Stop_Plot_Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.Stop_Plot_Button.setObjectName("Stop_Plot_Button")
        self.verticalLayout.addWidget(self.Stop_Plot_Button)
        self.Device_List.setWidget(self.dockWidgetContents_Device_List)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Device_List)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/07.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_File.setIcon(icon)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/images/10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/images/01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/images/09.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionMessage_Window = QtWidgets.QAction(MainWindow)
        self.actionMessage_Window.setObjectName("actionMessage_Window")
        self.actionData_Show_View = QtWidgets.QAction(MainWindow)
        self.actionData_Show_View.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/images/14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData_Show_View.setIcon(icon4)
        self.actionData_Show_View.setObjectName("actionData_Show_View")
        self.actionReal_Time_Information = QtWidgets.QAction(MainWindow)
        self.actionReal_Time_Information.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/images/15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReal_Time_Information.setIcon(icon5)
        self.actionReal_Time_Information.setObjectName("actionReal_Time_Information")
        self.actionPos_Plot = QtWidgets.QAction(MainWindow)
        self.actionPos_Plot.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/images/16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPos_Plot.setIcon(icon6)
        self.actionPos_Plot.setObjectName("actionPos_Plot")
        self.actionAngle_Plot = QtWidgets.QAction(MainWindow)
        self.actionAngle_Plot.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pic/images/18.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAngle_Plot.setIcon(icon7)
        self.actionAngle_Plot.setObjectName("actionAngle_Plot")
        self.actionSpeed_Plot = QtWidgets.QAction(MainWindow)
        self.actionSpeed_Plot.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/pic/images/19.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpeed_Plot.setIcon(icon8)
        self.actionSpeed_Plot.setObjectName("actionSpeed_Plot")
        self.actionAltitude_Plot = QtWidgets.QAction(MainWindow)
        self.actionAltitude_Plot.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/pic/images/17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAltitude_Plot.setIcon(icon9)
        self.actionAltitude_Plot.setObjectName("actionAltitude_Plot")
        self.actionStatus_Bar = QtWidgets.QAction(MainWindow)
        self.actionStatus_Bar.setObjectName("actionStatus_Bar")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/pic/images/02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon10)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/pic/images/21.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCascade.setIcon(icon11)
        self.actionCascade.setObjectName("actionCascade")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionSupport = QtWidgets.QAction(MainWindow)
        self.actionSupport.setObjectName("actionSupport")
        self.actionUpdates = QtWidgets.QAction(MainWindow)
        self.actionUpdates.setObjectName("actionUpdates")
        self.actionAbout_Saic_Position_Manager = QtWidgets.QAction(MainWindow)
        self.actionAbout_Saic_Position_Manager.setObjectName("actionAbout_Saic_Position_Manager")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/pic/images/08.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLog.setIcon(icon12)
        self.actionLog.setObjectName("actionLog")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/pic/images/03.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon13)
        self.actionStart.setObjectName("actionStart")
        self.actionSuspend = QtWidgets.QAction(MainWindow)
        self.actionSuspend.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/pic/images/04.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuspend.setIcon(icon14)
        self.actionSuspend.setObjectName("actionSuspend")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/pic/images/05.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon15)
        self.actionStop.setObjectName("actionStop")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/pic/images/06.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon16)
        self.actionClear.setObjectName("actionClear")
        self.actionTile = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/pic/images/20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTile.setIcon(icon17)
        self.actionTile.setObjectName("actionTile")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLog)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuView.addAction(self.actionData_Show_View)
        self.menuView.addAction(self.actionReal_Time_Information)
        self.menuView.addAction(self.actionPos_Plot)
        self.menuView.addAction(self.actionAngle_Plot)
        self.menuView.addAction(self.actionSpeed_Plot)
        self.menuView.addAction(self.actionAltitude_Plot)
        self.menuTools.addAction(self.actionPreferences)
        self.menuWindow.addAction(self.actionTile)
        self.menuWindow.addAction(self.actionCascade)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuHelp.addAction(self.actionSupport)
        self.menuHelp.addAction(self.actionUpdates)
        self.menuHelp.addAction(self.actionAbout_Saic_Position_Manager)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen_File)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionLog)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionSuspend)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTile)
        self.toolBar.addAction(self.actionCascade)

        self.retranslateUi(MainWindow)
        self.actionStart.triggered.connect(self.Open_Button.click)
        self.actionStop.triggered.connect(self.Close_Button.click)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuView.setTitle(_translate("MainWindow", "视图"))
        self.menuTools.setTitle(_translate("MainWindow", "工具"))
        self.menuWindow.setTitle(_translate("MainWindow", "窗口"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.Device_List.setWindowTitle(_translate("MainWindow", "设备列表"))
        self.Serial_GroupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.Lab_Serial_1.setText(_translate("MainWindow", "串口检测："))
        self.Check_Button.setText(_translate("MainWindow", "检测串口"))
        self.Lab_Serial_2.setText(_translate("MainWindow", "串口选择："))
        self.Lab_Serial_3.setText(_translate("MainWindow", "波特率："))
        self.Baudrate_ComboBox.setItemText(0, _translate("MainWindow", "460800"))
        self.Baudrate_ComboBox.setItemText(1, _translate("MainWindow", "500000"))
        self.Baudrate_ComboBox.setItemText(2, _translate("MainWindow", "2400"))
        self.Baudrate_ComboBox.setItemText(3, _translate("MainWindow", "4800"))
        self.Baudrate_ComboBox.setItemText(4, _translate("MainWindow", "9600"))
        self.Baudrate_ComboBox.setItemText(5, _translate("MainWindow", "14400"))
        self.Baudrate_ComboBox.setItemText(6, _translate("MainWindow", "19200"))
        self.Baudrate_ComboBox.setItemText(7, _translate("MainWindow", "38400"))
        self.Baudrate_ComboBox.setItemText(8, _translate("MainWindow", "57600"))
        self.Baudrate_ComboBox.setItemText(9, _translate("MainWindow", "76800"))
        self.Baudrate_ComboBox.setItemText(10, _translate("MainWindow", "12800"))
        self.Baudrate_ComboBox.setItemText(11, _translate("MainWindow", "115200"))
        self.Baudrate_ComboBox.setItemText(12, _translate("MainWindow", "230400"))
        self.Lab_Serial_4.setText(_translate("MainWindow", "数据位："))
        self.Bytesize_ComboBox.setItemText(0, _translate("MainWindow", "8"))
        self.Bytesize_ComboBox.setItemText(1, _translate("MainWindow", "7"))
        self.Bytesize_ComboBox.setItemText(2, _translate("MainWindow", "6"))
        self.Bytesize_ComboBox.setItemText(3, _translate("MainWindow", "5"))
        self.Lab_Serial_5.setText(_translate("MainWindow", "校验位："))
        self.Parity_ComboBox.setItemText(0, _translate("MainWindow", "N"))
        self.Lab_Serial_6.setText(_translate("MainWindow", "停止位："))
        self.Stopbits_ComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.Open_Button.setText(_translate("MainWindow", "打开串口"))
        self.Close_Button.setText(_translate("MainWindow", "关闭串口"))
        self.Lab_Serial_7.setText(_translate("MainWindow", "已接收："))
        self.Lab_Serial_8.setText(_translate("MainWindow", "已发送："))
        self.groupBox_2.setTitle(_translate("MainWindow", "杆臂向量"))
        self.Setting_Button.setText(_translate("MainWindow", "导入设置"))
        self.label_X.setText(_translate("MainWindow", "X轴："))
        self.label_Y.setText(_translate("MainWindow", "Y轴："))
        self.label_Z.setText(_translate("MainWindow", "Z轴："))
        self.groupBox.setTitle(_translate("MainWindow", "绘图设置"))
        self.Start_Plot_Button.setText(_translate("MainWindow", "开始绘图"))
        self.Stop_Plot_Button.setText(_translate("MainWindow", "停止绘图"))
        self.actionOpen_File.setText(_translate("MainWindow", "打开"))
        self.actionOpen_File.setToolTip(_translate("MainWindow", "打开文件"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionClose.setToolTip(_translate("MainWindow", "关闭菜单"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionSave.setToolTip(_translate("MainWindow", "保存文件"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setToolTip(_translate("MainWindow", "退出程序"))
        self.actionMessage_Window.setText(_translate("MainWindow", "Message Window"))
        self.actionData_Show_View.setText(_translate("MainWindow", "数据收发栏"))
        self.actionData_Show_View.setToolTip(_translate("MainWindow", "数据收发栏"))
        self.actionReal_Time_Information.setText(_translate("MainWindow", "实时信息栏"))
        self.actionReal_Time_Information.setToolTip(_translate("MainWindow", "实时信息栏"))
        self.actionPos_Plot.setText(_translate("MainWindow", "经纬度绘图栏"))
        self.actionPos_Plot.setToolTip(_translate("MainWindow", "经纬度绘图栏"))
        self.actionAngle_Plot.setText(_translate("MainWindow", "姿态角绘图栏"))
        self.actionAngle_Plot.setToolTip(_translate("MainWindow", "姿态角绘图栏"))
        self.actionSpeed_Plot.setText(_translate("MainWindow", "车速绘图栏"))
        self.actionSpeed_Plot.setToolTip(_translate("MainWindow", "车速绘图栏"))
        self.actionAltitude_Plot.setText(_translate("MainWindow", "高度绘图栏"))
        self.actionAltitude_Plot.setToolTip(_translate("MainWindow", "高度绘图栏"))
        self.actionStatus_Bar.setText(_translate("MainWindow", "Status Bar"))
        self.actionPreferences.setText(_translate("MainWindow", "设置"))
        self.actionPreferences.setToolTip(_translate("MainWindow", "设置"))
        self.actionCascade.setText(_translate("MainWindow", "次级展开窗口"))
        self.actionCascade.setToolTip(_translate("MainWindow", "次级展开窗口"))
        self.actionInstructions.setText(_translate("MainWindow", "指导手册"))
        self.actionInstructions.setToolTip(_translate("MainWindow", "指导手册"))
        self.actionSupport.setText(_translate("MainWindow", "技术支持"))
        self.actionSupport.setToolTip(_translate("MainWindow", "技术支持"))
        self.actionUpdates.setText(_translate("MainWindow", "软件更新"))
        self.actionUpdates.setToolTip(_translate("MainWindow", "软件更新"))
        self.actionAbout_Saic_Position_Manager.setText(_translate("MainWindow", "关于Saic Position Manager"))
        self.actionAbout_Saic_Position_Manager.setToolTip(_translate("MainWindow", "关于Saic Position Manager"))
        self.actionLog.setText(_translate("MainWindow", "记录数据"))
        self.actionLog.setToolTip(_translate("MainWindow", "记录数据"))
        self.actionStart.setText(_translate("MainWindow", "开始"))
        self.actionSuspend.setText(_translate("MainWindow", "暂停"))
        self.actionStop.setText(_translate("MainWindow", "停止"))
        self.actionStop.setToolTip(_translate("MainWindow", "停止"))
        self.actionClear.setText(_translate("MainWindow", "清除"))
        self.actionClear.setToolTip(_translate("MainWindow", "清除接收的数据"))
        self.actionTile.setText(_translate("MainWindow", "平铺窗口"))
        self.actionTile.setToolTip(_translate("MainWindow", "平铺窗口"))

import apprcc_rc
